### ISSUE TITLE
Causes failure when used with ember-addons

### ISSUE THREAD

**Issue by mfeckie** [draios/ember-typescript2#3]
Immediately following install of `ember-typescript2` on a previously working application I can no longer execute the dummy app.

Error is `vendor.js:249 Uncaught Error: Could not find module 'dummy/app' imported from '(require)'`

**Comment by maerten** [comment]
Hi!

Thanks for reporting this issue.

I can't seem to reproduce the issue on a newly generated addon...

Which versions of Ember-CLI & Typescript are you using?
Are you using any other addons inside your application?

Thanks!
